image: andthensome/docker-node-rsync

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn build
            - rsync -av --delete $BITBUCKET_CLONE_DIR/dist/. $SSH_USERNAME@$SSH_HOST:public_html/api
            - rsync -av --delete $BITBUCKET_CLONE_DIR/dist/. $SSH_USERNAME@$SSH_HOST:subdomains/staging/api
