language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
    - node_modules
    - functions/node_modules
notifications:
  slack:
    secure: ozWqacpXLS7nsAKT8x5IF2Z9TLVZVkRJQgQo5reP9NjhCHF9M5aegVLi9u+6QKvJLHAHmCRu/4YXpJxo5QaHV1Qlct/D0DUBG9WV3YbK5tnBlaxv9uyohOf4UR84X1mIEn5Bov4KPC0fxYLz1MFaEznauqLnpacRhuKrxBt7WqkhrjmVHQbNEq4Iu4UxXTqHzVZcv/PR7yetYn8R9ISt2dLlEj5ptkWhTlRL9mi4Ls6Tf35TTbQU5CnTp/KlBM3I/RHaB429b1jDwXN4N0b3TE8ePhM2tfZ5wBlmTtxblxJYQkZ4hAN77kRP/0DwtdHjDeuYbr3drdPai+EZun2LiXEaALlXUKjisWaaFX/Om8rz8LA06SfY939A03Iqx58eWOH92d+VOzyOpi+m3JVM0G9DqLSpQbx5hMrDp6stWonFmZkOQr5Clcf8j2Y8c3m1E8oQ+0vYgULA+ylDqGsU6bAGUMeCUUPg4zknJoob7gEejPSzF5qybssjEfJaXgggHuUsnL8jh5ed2rZA5VC8G4P2MESLNghXHeWYTYbELVKr7aYUhjj+OH/a9iko66iekTNoTPbfzkJcdaGnFdSE4ODY/xvnzx5mUu25nVzJoDEPUAwXi44kvIq/+XWyOjnOBpfIwFjJ4FyYXPIWMC0Nn8OCkciWq5wKjT/X+INfP5c=

firebase: &firebase
  provider: firebase
  skip_cleanup: true
  token:
    secure: Lapn6iiUuzvke97kEN4E5qOg7EH5wTs9zH7ZW76LGULeuZBFwORAVmm0rXhSW/+jRwqy+w2r5hTIvU/1JZTpXmUn+kIR2Q4h/wBxTazPx2JJ6SwjK9tXupZC/rttO+Tl2TpTXOiuGz+yEKP2XfSowjXOZS4viD2YQklQDF+ot7P7e/RkKaoHkEjuUKb0eIGUeyvkGJqpeOLDLD3lJMr710BvhFRiaYy5ng5Adcit7RIYsRxtqE9HHc6wY5BM4JgRhzgXuSaK0j6J/I0uxXEvUWyc6kMn+SbBz3c89r/N8f09KhvdGZ2wVOAoClcm8w67xjB/3Mk3WZKmGS6gmhf3ugLrl4cKofEwCho7WD3bxQBnjtdia1Vuixx851x9x3IiHEPFDau2sYYCwBZNuBDC8G9zbM4gJY51lbXopdFlVtJ/5wfyNqjPpejRps24T+pKKlp3mQ2PRl/8qy/AkOgVpuESc1dDsZpYZGYxduN9SLqmghNAikR0QH9vKQZ+r2DOcTFW2VBcXX7nJhIOAJDwhO/2nnsELzTG+82ly6DzthumsU9kAIhkYyGR4irTpfGesfDxSwv6ZNFnDiQq5NqmAYSnHfsqEGTgegQorpQ0Pwa6N1uH/t8HMS1Kz/XV+9hl6AP4MinU+I6VJnwR05giu2LBCaUkgvcmofYt8sbS7cU=

jobs:
  include:
    - stage: test
      script:
        - cd functions
        - yarn
        - yarn test --coverage --coverageReporters=text-lcov | coveralls
    - stage: deploy
      if: branch = master
      script: skip
      deploy:
        <<: *firebase
        project: hkfd-email
