language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
    - node_modules
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/node_modules/.cache
env:
  global:
    - ENVIRONMENT=staging
notifications:
  slack:
    secure: sd+z7P3ZK52RXjEoLNfZKATpYK+yKUNMZMXmqY4TtKh4Bkzrsq38/f845QWrpje5EmMuCSkiB9q4fA3g38rls50oaztiGdGYSxXOpcJr/kjTydsY7PREevIjN7s3yU3o5c+BX8jbn16iQeEdTffcRKH2upN5JBAcQfrqIVQHZdwPIFBa0nuZhRiysGL7kKuiPtwWZs2sNVBF+4RIj1kzJac6sL8BwUhMnbN2KYrUfHjiw9vuobvt3gTL36tNOzUVWJ5e2zxB+XphQr7skYrSKartSo0dTm4nd3HJFkxKv8aGP9maLdu5GcHeRJqqeZZB1uiUjFk3yKOBv2jc+JEtkjyEY6T1cvm2TdsEHcyHruBrAR+YxEGOcwTS6yUB/Hjo4IbSMhqgqq1baxRYS43GYDiWm+gEHRcGL0oUXXwiyYf0njSLPelDBm1Cu0hNRYek+CL8R/LtcoBp8f9mFe0ogYyRyOdeP94Mf8t1uAjbQLmu6orfSgbw0iVafgvEpehXxNSmMslW1XtkBTqc/cpJG81sqSD+y9arm6W+CLmXWvj8OpwJ+oMue1Gx0+dWSDHMN+Q8C91ClfTlrutZQgpx0Hh6QOFPpVXrhTaiOPUn0OovDBP9oR/tkv/G7/QmPaQX5Ffd82qqhjy3pGGDOgjXzsAtgEr17fCwIzGED/JzsVg=

jobs:
  include:
    - stage: Pre-cache
      script: skip

    - stage: Test
      name: 'Spec: Browser'
      script:
        - yarn test:browser --progress=false --browsers=HeadlessChromeNoSandbox --code-coverage
        - cat coverage/lcov.info | yarn coveralls

    - stage: Test
      name: 'Spec: Server'
      script:
        - yarn build:ssr
        - yarn test:server

    - stage: Test
      name: E2E
      sudo: required
      addons:
        chrome: stable
      script: yarn e2e --protractor-config=protractor-ci.conf.js

    - stage: Deploy
      if: branch = master
      name: Deploy Production
      script: skip
      deploy:
        provider: heroku
        app: hkfd
        api_key:
          secure: ag7XXYCcj87LqTStX0NOp2/uUGA9tM00z5yMKk8AqqAEaBAneUVaWYy/17OT2fCKAr/Xfn6qw+WApG6BDTXyZTPZefVod9XyRh0GTZxUTQlKLCTev2d7+WVuu1wKHqYmwST0pHLmIqQCJvxfx1QSXgPlMXyi19oep13n3ucVEviJfluNyF4r4xYmOhkXJi2emZzgaBs0qsAm9ksFBKxs9rH7dZbTrOdox+TkLagL6/clp5AR17Hb86D8fJmvs9h0opC60C5JH4qqHyXc9YjFV+MhbKIUW7qsX0+Vy580XxZRybSjlOA3dDX/X4xqI1QpcBCtFko/phQHJGUAYBaFAEdV8QfdlbyYquv9j5BAEms0aI5YyPwOxfwrTJaI4p/ywnuHGWlS5J1YoNIfjHmuSlKAYMV+/ABgZEC8L+J1oMmoHSbmfQqIICRMsb1hvrNCrBgT14wGVFcL5FQ+U9eFPlTW+0HmHhDDDFMhkTfGvByFMA5g80nNwO3R3kLEzJ/HbhYI+cAUz9Lp2v5w7Lh0HW9Wict+y/IWFCtGI2cK3rcZNg5UQywrze5r6JqIojuFL9zKIVsJIwqXFs8pHRp4POSAgLN/fg5k9UtLmki3/DEDfprvR2UEMgPYcjgNDbSh4BhPgJ4nwySjiq5KkMwi/yOs67C2TISzNyicG3T534o=
