image: andthensome/docker-node-rsync

pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - yarn
            - ./node_modules/.bin/ng build --prod
            - rsync -av --delete $BITBUCKET_CLONE_DIR/dist/. $SSH_USERNAME@$SSH_HOST:public_html
    dev:
      - step:
          deployment: staging
          caches:
            - node
          script:
            - yarn
            - ./node_modules/.bin/ng build --prod
            - rsync -av --delete $BITBUCKET_CLONE_DIR/dist/. $SSH_USERNAME@$SSH_HOST:subdomains/staging
