image: andthensome/docker-node-rsync

pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - git submodule sync && git submodule update --init --recursive
            - yarn && yarn build
            - rsync -av --exclude=api --exclude=form --exclude='sitemap.xml' --delete dist/. $SSH_USERNAME@$SSH_HOST:public_html
    dev:
      - step:
          deployment: staging
          caches:
            - node
          script:
            - git submodule sync && git submodule update --init --recursive
            - yarn && yarn build
            - rsync -av --exclude=api --exclude=form --exclude='sitemap.xml' --delete dist/. $SSH_USERNAME@$SSH_HOST:subdomains/staging
