image: andthensome/docker-node-rsync

pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - yarn
          script:
            - git submodule sync && git submodule update --init --recursive
            - yarn && yarn build
            - rsync -av --exclude api --delete dist/. $SSH_USERNAME@$SSH_HOST:public_html
    dev:
      - step:
          deployment: staging
          caches:
            - yarn
          script:
            - git submodule sync && git submodule update --init --recursive
            - yarn && yarn build
            - rsync -av --exclude api --delete dist/. $SSH_USERNAME@$SSH_HOST:subdomains/staging
definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn/v1
