version: 2
machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
jobs:
  build:
    working_directory: ~/heckford-angular
    docker:
      - image: circleci/node:9.11-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: update Chromedriver
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: spec
          command: yarn run test --single-run --no-progress --browser=ChromeNoSandbox
      - run:
          name: e2e
          command: xvfb-run -a yarn run e2e --no-progress --config=protractor-ci.conf.js
